### ISSUE TITLE
关于使用suffix尾缀的问题

### ISSUE THREAD

**Issue by zc0xb** [LEOYoon-Tsaw/Cangjie6#19]
您好，想请教个问题
就是关于尾缀的使用
在学习您的文章[Schema.yaml 詳解](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md)时了解到reverse_lookup_translator在后续被替代了，然后我看cangjie5里的reverse_lookup_translator的方式也在cangjie6里被替换成 affix_segmentor + 正常translator的方式
但是我对suffix尾缀的配置和使用一直有些疑问：
在cangjie5
```
 translators:
    - reverse_lookup_translator
reverse_lookup:
  dictionary: luna_pinyin
  prism: luna_quanpin
  prefix: "`"
  suffix: "'"
  tips: 〔拼音〕
recognizer:
  patterns:
    reverse_lookup: "`[a-z]*'?$|[a-z]+'$"` 
```
使用配置里尾缀'正常
但在[cangjie6](https://github.com/LEOYoon-Tsaw/Cangjie6/blob/master/cangjie6.schema.yaml)里
使用尾缀；会造成候选直接消失，且默认第一个候选，如果直接空格上屏还好。
但如果要选择其他候选，需要移动caret位置，然后造成尾缀 ；遗留在input text里。

https://github.com/user-attachments/assets/68eae9df-a3c0-4afb-8730-a40b5e356efb

我不知道这是librime后来变化还是我理解使用不当造成的？
